[build]
  command = "npm run build"
  publish = "dist/public"
  base = "."

[build.environment]
  NODE_VERSION = "18"

# Redirect for 404 page
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Redirect for success page
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

# Form submission success redirect
[[redirects]]
  from = "/thanks"
  to = "/success.html"
  status = 200

# Redirect to home for SPA routing (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle form submissions
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

# Form handler options
[build.processing.html]
  pretty_urls = true