[build]
  command = "npm run build"
  publish = "dist/public"
  base = "."

[build.environment]
  NODE_VERSION = "18"

# Redirect form submissions to success page
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

# Redirect to home for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle form submissions
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"